FROM node:alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# ARG from docker action build-args
ARG PORT

ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_NAME

ARG BASE_FRONT_URL

ARG SMTP_LOGIN
ARG SMTP_PASS
ARG SMTP_LOGIN
ARG SMTP_SERVER
ARG EMAIL_SENDER

ARG JWT_SECRET
ARG JWT_EXPIRATION_TIME

ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CALLBACK_URL


#env from arguments
ENV PORT=$PORT

ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME

ENV BASE_FRONT_URL=$BASE_FRONT_URL

ENV SMTP_LOGIN=$SMTP_LOGIN
ENV SMTP_PASS=$SMTP_PASS
ENV SMTP_SERVER=$SMTP_SERVER
ENV EMAIL_SENDER=$EMAIL_SENDER

ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRATION_TIME=$JWT_EXPIRATION_TIME

ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_CALLBACK_URL=$GOOGLE_CALLBACK_URL

EXPOSE 3306
EXPOSE 3333
CMD [ "node", "dist/main.js" ]